## 将xlsx数据转为pt文件

In [ ]:
import torch
import pandas as pd

data_path = './tspData.csv'

# 读取csv文件
data = pd.read_csv(data_path)
df = data
df.head(10)

In [3]:
import numpy as np

X_columns = [f'X_{i}' for i in range(15)]
Y_columns = [f'Y_{i}' for i in range(15)]
X_data = df[X_columns].values
Y_data = df[Y_columns].values

input = np.stack([X_data, Y_data], axis=2)

print('结果的形状：', input.shape)
input[0]

结果的形状： (20000, 15, 2)


array([[372, 275],
       [229, 290],
       [100, 254],
       [133,  27],
       [297, 260],
       [ 56, 179],
       [208, 237],
       [130, 154],
       [ 14, 199],
       [141,  75],
       [155,  17],
       [159, 266],
       [215, 299],
       [ 24, 121],
       [ 59,  25]], dtype=int64)

In [4]:
sol_data = df['sol']
processed_sol = []

for sol in sol_data:
    # 按'-'分割字符串，并去除最后一个元素（因为最后一个是回到起点的0）
    cities = sol.split('-')[:-1]
    # 将城市编号转换为整数
    cities = list(map(int, cities))
    processed_sol.append(cities)

# 将列表转换为numpy数组并重塑形状
label = np.array(processed_sol)
print(label)

[[ 0  1 12 ...  7  6  4]
 [ 0 11 14 ...  3  6  4]
 [ 0 12  5 ...  7 13 11]
 ...
 [ 0 13  2 ...  8  6  9]
 [ 0 13  2 ... 14  1  8]
 [ 0 13  2 ...  4  9  6]]


In [5]:
input_tensor = torch.tensor(input, dtype=torch.float32)
label_tensor = torch.tensor(label, dtype=torch.long)

print(input_tensor.shape)
print(label_tensor.shape)


torch.save({
    'input': input_tensor,
    'label': label_tensor
}, 'tsp_data.pt')


torch.Size([20000, 15, 2])
torch.Size([20000, 15])
